###  Naive Bayes Classifiers is a collection of classifiers alogorithm based on bayes theorem.It is not a single algorithm but a family of algorithm which shares a common principle ie. every pair of feature should be independent to each other.
## BAYES THEOREM
## $$ P(A|B) = \frac {P(A).P(B|A)} {P(B)} $$
where A and B are events and P(B) ? 0.

Basically, we are trying to find probability of event A, given the event B is true. Event B is also termed as evidence.
P(A) is the priori of A (the prior probability, i.e. Probability of event before evidence is seen). The evidence is an attribute value of an unknown instance(here, it is event B).
P(A|B) is a posteriori probability of B, i.e. probability of event after evidence is seen


or 

$$ \text {Posterior Probability}  = \frac {\text(Prior Probability).\text(Likelihood)} {\text (Normalizing Constant)} $$
<p><b>Posterior Probability</b> - Which Represents the degree to which we believe a                       given model accurately describes the situation given the                       available data and all of our prior knowledge </p>

<p><b>Prior Probability</b> - Which Describe the Degree to which we believe the model
                   accurately describes reality based on all of our information <p>
    
<p> <b>Likelihood</b> - which describes how well the model predicts the data </p>
    
<p><b>Normalizing constant</b> - The constant that makes the posterior density                         INTEGRATE to one</p>
    

## Types of classifiers

### Gaussian Naive Bayes classifier

#### In Gaussian Naive Bayes, continuous values associated with each feature are assumed to be distributed according to a Gaussian distribution. A Gaussian distribution is also called Normal distribution.

### Multinomial Naive Bayes: Feature vectors represent the frequencies with which certain events have been generated by a multinomial distribution. This is the event model typically used for document classification.
### Bernoulli Naive Bayes: In the multivariate Bernoulli event model, features are independent booleans (binary variables) describing inputs. Like the multinomial model, this model is popular for document classification tasks, where binary term occurrence(i.e. a word occurs in a document or not) features are used rather than term frequencies(i.e. frequency of a word in the document).

In [4]:
import pandas as pd
import numpy as np
data  =pd.read_csv("F:/Data_science/seaborn-data/navie_bays_play.csv")

In [3]:
data

outlook temperature humidity  windy play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

### $$ P({A} |{B}) = \frac {P(A)P(B|A)} {P(B)}$$

### $$ P(A) = \text{P(play=yes) } $$
$$ P(B)  = P(outlook=rainy)P(tempreature=mild)P(humidity=normal)P(Wind=strong) $$

In [19]:
yes=data['play'][data['play']=='yes'].count()

In [13]:
total=data['play'].count()

In [15]:
total

14

In [20]:
p_yes=yes/total
p_yes

0.6428571428571429

In [26]:
outlook_rainy=data['outlook'][data['outlook']=='rainy'].count()
outlook_rainy

5

In [27]:
p_outlook_rainy=outlook_rainy/total
p_outlook_rainy

0.35714285714285715

In [30]:
temp_mild=data['temperature'][data['temperature']=='mild'].count()
temp_mild

6

In [31]:
p_temp_mild=temp_mild/total
p_temp_mild

0.42857142857142855

In [32]:
hum_nor=data['humidity'][data['humidity']=='normal'].count()
p_hum_nor=hum_nor/total
p_hum_nor

0.5

In [34]:
windy_true = data['windy'][data['windy']==True].count()
windy_true

6

In [35]:
p_windy_true = windy_true / total
p_windy_true

0.42857142857142855

In [37]:
data['temperature'] = data['temperature'].map({
    'hot':1, 'mild':2,'cool':3
})

In [38]:
data['outlook'] = data['outlook'].map({
    'sunny':1, 'rainy':2, 'overcast':3
})

In [39]:
data['humidity'] = data['humidity'].map({
    'high':1,'normal':2
})

In [40]:
data['windy'] = data['windy'].map({
    True:1,False:2
})

In [41]:
data

outlook  temperature  humidity  windy play
0         1            1         1      2   no
1         1            1         1      1   no
2         3            1         1      2  yes
3         2            2         1      2  yes
4         2            3         2      2  yes
5         2            3         2      1   no
6         3            3         2      1  yes
7         1            2         1      2   no
8         1            3         2      2  yes
9         2            2         2      2  yes
10        1            2         2      1  yes
11        3            2         1      1  yes
12        3            1         2      2  yes
13        2            2         1      1   no

In [42]:
feature,target=data.drop("play",axis=1),data['play']

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
from sklearn.naive_bayes import MultinomialNB


In [64]:
model=MultinomialNB()
model.fit(feature,target)
pred=model.predict([[1,1,1,2]])
pred

array(['yes'], dtype='<U3')

# IRIS --> Multinomial

In [65]:
from sklearn.datasets import load_iris
iris=load_iris()

In [68]:
feature,target=iris['data'],iris['target']

In [82]:
X_train,X_test,y_train,y_test=train_test_split(feature,target)
model=MultinomialNB()
model.fit(X_train,y_train)
pred=model.predict(X_test)

In [84]:
feature[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [86]:
target[:5]

array([0, 0, 0, 0, 0])

In [71]:
pred

array([0, 0, 1, 0, 0, 0, 2, 0, 2, 2, 0, 0, 2, 1, 0, 2, 2, 2, 2, 0, 2, 0,
       2, 1, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0])

In [72]:
y_test

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 1, 2, 1, 0, 2, 0,
       2, 1, 1, 0, 0, 2, 2, 0, 1, 0, 0, 1, 0, 1, 0, 0])

In [79]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,r2_score

In [74]:
accuracy_score(y_test,pred)


0.7894736842105263

In [75]:
confusion_matrix(y_test,pred)

array([[19,  0,  0],
       [ 0,  4,  8],
       [ 0,  0,  7]], dtype=int64)

In [78]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.33      0.50        12
           2       0.47      1.00      0.64         7

   micro avg       0.79      0.79      0.79        38
   macro avg       0.82      0.78      0.71        38
weighted avg       0.90      0.79      0.78        38



In [81]:
r2_score(y_test,pred)

0.6398104265402846

##  4 Applications of Naive Bayes Algorithms
1. Real time Prediction: Naive Bayes is an eager learning classifier and it is sure fast. Thus, it could be used for making predictions in real time.
2. Multi class Prediction: This algorithm is also well known for multi class prediction feature. Here we can predict the probability of multiple classes of target variable.
3. Text classification/ Spam Filtering/ Sentiment Analysis: Naive Bayes classifiers mostly used in text classification (due to better result in multi class problems and independence rule) have higher success rate as compared to other algorithms. As a result, it is widely used in Spam filtering (identify spam e-mail) and Sentiment Analysis (in social media analysis, to identify positive and negative customer sentiments)
4. Recommendation System: Naive Bayes Classifier and Collaborative Filtering together builds a Recommendation System that uses machine learning and data mining techniques to filter unseen information and predict whether a user would like a given resource or not
 

## text classification

In [87]:
msg1="hello i m sparsh jain."
msg2="50% off garb the deals."
from sklearn.feature_extraction.text import CountVectorizer

In [88]:
obj1=CountVectorizer()

In [90]:
data=obj1.fit_transform([msg1,msg2]) ## the fit_transform works similar to fit besides it return the values.

In [91]:
data

<2x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [92]:
data.data

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [94]:
obj1.vocabulary_ ## Bag of words

{'hello': 3,
 'sparsh': 6,
 'jain': 4,
 '50': 0,
 'off': 5,
 'garb': 2,
 'the': 7,
 'deals': 1}

In [95]:
print(obj1.fit_transform(["hello world how are you ","hello hello hello bye",
                        "let's hello to bye bye to hello good to go "]))

  (0, 9)	1
  (0, 0)	1
  (0, 5)	1
  (0, 8)	1
  (0, 4)	1
  (1, 1)	1
  (1, 4)	3
  (2, 2)	1
  (2, 3)	1
  (2, 7)	3
  (2, 6)	1
  (2, 1)	2
  (2, 4)	2


In [96]:
obj1.vocabulary_

{'hello': 4,
 'world': 8,
 'how': 5,
 'are': 0,
 'you': 9,
 'bye': 1,
 'let': 6,
 'to': 7,
 'good': 3,
 'go': 2}